twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        app_name: '%app.name%'
        app_description: '%app.description%'
        app_version: '%app.version%'
        app_favicon: '%app.favicon%'
        app_logo: '%app.logo%'
        app_inactivity_timeout: '%app.session.inactivity_timeout%'

when@test:
    twig:
        strict_variables: true
