services:
  app:
    environment:
      APP_ENV: dev
      # En dev : réinitialise le schéma + régénère les données factices à chaque démarrage des conteneurs.
      FORCE_DB_INIT: "true"

  mysql:
    ports:
      - "3306:3306"
